# Generated by Django 3.2.9 on 2021-11-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_spotify', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
