# Generated by Django 3.2.9 on 2021-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifycred',
            name='notifications',
            field=models.BooleanField(default=1),
        ),
    ]
