# Generated by Django 3.2.9 on 2021-11-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_spotifycred_notifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpotifyCred',
            new_name='Spotify_Notification_Cred',
        ),
    ]
