# Generated by Django 3.2.9 on 2021-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_starred_concerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starred_concerts',
            name='id',
        ),
        migrations.AlterField(
            model_name='starred_concerts',
            name='concert_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
