# Generated by Django 3.2.9 on 2021-11-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211117_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='starred_concerts',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='starred_concerts',
            name='concert_id',
            field=models.CharField(max_length=100),
        ),
    ]
