# Generated by Django 3.2.9 on 2021-12-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211117_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starred_concerts',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
