# Generated by Django 3.2.9 on 2021-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_starred_concerts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starred_concerts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
